### ISSUE TITLE
Code for Bandwidth Calculation

### ISSUE THREAD

**Issue by nikhil1008** [chamain/QuanNet#1]
Hi could you also upload bandwidth calculation code please ? That would be really helpful.

**Comment by chamain** [comment]
For the exact BW calculation, you may have to build JPEG2000 and change the quantization step sizes you leaned in the codec. Use this repo: https://github.com/uclouvain/openjpeg. The hardest part is to locate the step sizes in C codes. Thanks.

**Comment by nikhil1008** [comment]
Thanks a lot for your response! 

Couple more questions : 
1. When you compare performance with **standard JPEG2000**, for benchmarking JPEG2000 bandwidth , do you specify quantization step as well or do you use standard quantization step given in OpenJpeg ? I see in the paper you use dLL1 = 4.0156 (section 4) and so on.  Is it for Y channel ? If so, what about C channel ? 

2. Do you incorporate truncation as well when calculating QuanNet Bandwidth ? If so , any pointers on how you do that using openJpeg. Do you also incorporate similar truncation in standard Jpeg DCT coefficients for fair comparison?

**Comment by chamain** [comment]
1. To produce the baseline for this paper, I didn't use the openJPEG codec. (But we observed similar claimed accuracy improvements and BW savings when we used the codec, results not published yet.). And for the baseline in this paper, I used same quantization for all 3 channels.

2. I didn't include truncation (mentioned in the paper as an experiment) for QuanNet Bandwidth. But if you use JPEG2000, it has its own bit stream truncation (EBCOT) algorithm.

**Comment by nikhil1008** [comment]
Thank you ! I'm trying to reproduce results from the paper. 

So, for fair bandwidth comparison , do you recommend to implement post-DWT quantization lossless compression like arithmetic coding or do you recommend to use OpenJPeg. Again, I'm trying to exactly replicate the results from the paper.
If you recommend to implement post-DWT quantization lossless techniques, could you please list exactly which techniques you used ?  

Thanks,

**Comment by chamain** [comment]
I recommend using OpenJPeg for fairer comparison since it has rate distortion optimizations inbuilt. To replicate the results of the paper, you can use post DWT arithmetic coding. I can provide you a script that I used. But may take sometime to locate it.

**Comment by nikhil1008** [comment]
sure, I can wait. Thank you so much !

**Comment by nikhil1008** [comment]
Could you also provide  quantization steps used in fig.5 for **baseline** ? Because some of the points are different from fig.2 baseline . (e.g. acc=90 b = 750 in fig.5) , I'm trying to get Fig.5 plot. 

specifically, dLL, dLH, dHL and dHH for 3 baseline points in fig.5 from the paper. 

Thanks,

**Comment by nikhil1008** [comment]
After training Quannet, following coefficients are  obtained for quantization step size for lambdaQ = 0.07. 
0.34277198, -0.        ,  0.33719128, -0., 0.35755655, -0. , -0, -0, 0.3939665 , -0.        , -0.        , -0.   
Couple of  questions  : 
1. How do you quantize for Qstep of 0 ? 
2. How is Bandwidth of Quannet smaller than baseline if quantization coefficients are approaching 0 ? Maybe I'm missing something. 
Thanks,

**Comment by chamain** [comment]
Hi @nikhil1008,
The weights are the reciprocals of of step sizes Q, for instance the step size for w_i = 0.34277198 is Q_i = 5*(1/(0.34277198)). Here 5 is the pre-scaling factor. See https://github.com/chamain/QuanNet/blob/d216cfaccabb4f080c96a554a13b70aa93402e3f/train.py#L79
 Now w_i = 0 means Q_i goes to infinity hence we don't have to transmit those channels.

**Comment by chamain** [comment]
> Could you also provide quantization steps used in fig.5 for **baseline** ? Because some of the points are different from fig.2 baseline . (e.g. acc=90 b = 750 in fig.5) , I'm trying to get Fig.5 plot.
> 
> specifically, dLL, dLH, dHL and dHH for 3 baseline points in fig.5 from the paper.
> 
> Thanks,

So to get different points on the baseline (Fig. 5) you have to scale* step sizes mentioned in the paper. (dLL1= 4.0156,dLH1=dHL1= 8.031, dHH1= 16.0625.) For instance you can get the BW=738, scale=4. Other points are (BW=593, scale=8),  (BW=464, scale=16).
